import AuthProvider from '@/lib/SessionProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Task | Auth',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="min-h-screen">
                    <Toaster/>
                    <AuthProvider>
                        {children}
                    </AuthProvider>
                </div>
            </body>
        </html>
    )
}
