import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import TopBar from '@/components/Globals/TopBar'
import AuthProvider from '@/lib/SessionProvider'
import { Toaster } from '@/components/ui/toaster'
import { getOrgs } from '@/actions/Organization'
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet"
import { ChevronLeft } from "lucide-react"
import LeftSideBar from '@/components/Globals/LeftSideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'T-ASK',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  const data = await getOrgs()

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider >
          <main className='w-full h-full'>
            <TopBar />
            <section className='mt-14 container'>
                {data.data && data.data.Organization && data.data.Organization.length > 0 && (
                  <>
                    <LeftSideBar orgs={data.data.Organization}  mobile={false} />
                    <Sheet>
                      <SheetTrigger className="md:hidden">
                        <div className="cursor-pointer z-50 fixed bg-greenshade px-2 py-1.5 bottom-10 right-0 rounded-l-md anime-enter">
                          <div className="flex items-center anime-enter1">
                            <ChevronLeft color="#fff" width={30} height={30} />
                            <ChevronLeft color="#fff" width={26} height={26} className="-ml-3" />
                            <ChevronLeft color="#fff" width={22} height={22} className="-ml-3" />
                          </div>
                        </div>
                      </SheetTrigger>
                      <SheetContent className="overflow-y-scroll">
                        <div className="mt-8">
                          <LeftSideBar orgs={data.data.Organization} mobile={true} />
                        </div>
                      </SheetContent>
                    </Sheet>
                  </>
                )}
              {children}
            </section>
            <Toaster />
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
